apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platformstorageapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: platformstorageapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: platformstorageapi
    spec:
      containers:
      - name: platformstorageapi
        image: {{ printf "%s" (pluck .Values.global.env .Values.IMAGE | first | default .Values.IMAGE._default) }}
        imagePullPolicy: Always
        env:
        - name: NP_STORAGE_LOCAL_BASE_PATH
          value: /var/storage
        - name: NP_STORAGE_AUTH_URL
          value: {{ printf "%s" (pluck .Values.global.env .Values.NP_STORAGE_AUTH_URL | first | default .Values.NP_STORAGE_AUTH_URL._default) }}
        - name: NP_STORAGE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: platformservices-secret
              key: storage_token
        volumeMounts:
        - name: storage
          mountPath: /var/storage

      volumes:
        - name: storage
          nfs:
            server: {{ printf "%s" (pluck .Values.global.env .Values.NP_STORAGE_NFS_SERVER | first | default .Values.NP_STORAGE_NFS_SERVER._default) }}
            path: /nfs
---
apiVersion: v1
kind: Service
metadata:
  name: platformstorageapi
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: platformstorageapi
