apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platformstorageapi
spec:
  replicas: {{ .Values.NP_STORAGE_REPLICAS }}
  selector:
    matchLabels:
      service: platformstorageapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: platformstorageapi
    spec:
      containers:
      - name: platformstorageapi
        image: {{ .Values.IMAGE }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ .Values.NP_STORAGE_REQUESTS_CPU }}
            memory: {{ .Values.NP_STORAGE_REQUESTS_MEMORY }}
          limits:
            cpu: {{ .Values.NP_STORAGE_LIMITS_CPU }}
            memory: {{ .Values.NP_STORAGE_LIMITS_MEMORY }}
        env:
        - name: NP_STORAGE_LOCAL_BASE_PATH
          value: /var/storage
        - name: NP_STORAGE_AUTH_URL
          value: {{ .Values.NP_STORAGE_AUTH_URL }}
        - name: NP_STORAGE_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: platformservices-secret
              key: storage_token
        - name: NP_PERMISSION_EXPIRATION_INTERVAL
          value: "{{ .Values.NP_PERMISSION_EXPIRATION_INTERVAL }}"
        - name: NP_PERMISSION_FORGETTING_INTERVAL
          value: "{{ .Values.NP_PERMISSION_FORGETTING_INTERVAL }}"
        - name: NP_STORAGE_ZIPKIN_URL
          value: {{ .Values.NP_STORAGE_ZIPKIN_URL }}
        - name: NP_STORAGE_ZIPKIN_SAMPLE_RATE
          value: "{{ .Values.NP_STORAGE_ZIPKIN_SAMPLE_RATE }}"
        - name: NP_CLUSTER_NAME
          value: "{{ .Values.NP_CLUSTER_NAME }}"
        - name: NP_STORAGE_API_KEEP_ALIVE_TIMEOUT
          value: "{{ .Values.NP_STORAGE_API_KEEP_ALIVE_TIMEOUT | quote }}"
        volumeMounts:
        - name: storage
          mountPath: /var/storage
      {{- if .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
      imagePullSecrets:
        - name: {{ .Values.DOCKER_LOGIN_ARTIFACTORY_SECRET_NAME }}
      {{- end }}
      volumes:
        - name: storage
          {{- if .Values.NP_STORAGE_PVC_CLAIM_NAME }}
          persistentVolumeClaim:
            claimName: {{ .Values.NP_STORAGE_PVC_CLAIM_NAME }}
          {{- else }}
          nfs:
            server: {{ .Values.NP_STORAGE_NFS_SERVER }}
            path: {{ .Values.NP_STORAGE_NFS_PATH }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_SESSION
  name: platformstorageapi
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: platformstorageapi
