apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformstorageapi
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: platformstorageapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: platformstorageapi
      {{- if .Values.secrets }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- end }}
    spec:
      containers:
      - name: platformstorageapi
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: tcp-web
          initialDelaySeconds: 10
          timeoutSeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: tcp-web
            protocol: TCP
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        env:
        - name: NP_STORAGE_LOCAL_BASE_PATH
          value: /var/storage
        - name: NP_STORAGE_AUTH_URL
          value: {{ .Values.NP_STORAGE_AUTH_URL }}
        - name: NP_STORAGE_AUTH_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 10 }}
{{- end }}
        - name: NP_PERMISSION_EXPIRATION_INTERVAL
          value: "{{ .Values.NP_PERMISSION_EXPIRATION_INTERVAL }}"
        - name: NP_PERMISSION_FORGETTING_INTERVAL
          value: "{{ .Values.NP_PERMISSION_FORGETTING_INTERVAL }}"
        - name: NP_CLUSTER_NAME
          value: "{{ .Values.NP_CLUSTER_NAME }}"
        - name: NP_STORAGE_API_KEEP_ALIVE_TIMEOUT
          value: "{{ .Values.NP_STORAGE_API_KEEP_ALIVE_TIMEOUT }}"
        - name: NP_CORS_ORIGINS
          value: {{ .Values.NP_CORS_ORIGINS | quote }}
        {{- if .Values.zipkin }}
        - name: NP_ZIPKIN_URL
          value: {{ .Values.zipkin.url }}
        - name: NP_ZIPKIN_SAMPLE_RATE
          value: {{ .Values.zipkin.sampleRate | default 0 | quote }}
        {{- end }}
        {{- if .Values.sentry }}
        - name: NP_SENTRY_DSN
          value: {{ .Values.sentry.dsn }}
        - name: NP_SENTRY_CLUSTER_NAME
          value: {{ .Values.sentry.clusterName }}
        - name: NP_SENTRY_SAMPLE_RATE
          value: {{ .Values.sentry.sampleRate | default 0 | quote }}
        {{- end }}
        volumeMounts:
        - name: storage
          mountPath: /var/storage
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ .toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: storage
          {{- if .Values.NP_STORAGE_PVC_CLAIM_NAME }}
          persistentVolumeClaim:
            claimName: {{ .Values.NP_STORAGE_PVC_CLAIM_NAME }}
          {{- else }}
          nfs:
            server: {{ .Values.NP_STORAGE_NFS_SERVER }}
            path: {{ .Values.NP_STORAGE_NFS_PATH }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_STORAGEAPI_SESSION
  name: platformstorageapi
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: tcp-web
  selector:
    service: platformstorageapi
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: platformstorageapi
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /api/v1/storage
        backend:
          serviceName: platformstorageapi
          servicePort: http
  {{- end }}
{{- end }}
