apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-storage
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.56.3.145"
    path: /exports
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-storage
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-jobs-storage
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.56.3.145"
    path: /exports
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-storage
  namespace: platform-jobs
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""