[build-system]
requires = [
    "pip",
    "setuptools",
    "wheel",
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
git_describe_command = "git describe --dirty --tags --long --match v*.*.*"

[tool.black]
exclude = '''
/(
      \.git
    | venv
    | __pycache__
)/
'''
