version: 2

jobs:
  test:
    working_directory: ~/workspace
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true

    steps:
      - checkout

      # NOTE: these are temporary steps until moved to docker
      - run:
          name: Configuring Docker Client
          command: |
            make -s gke_login

      - run:
          name: Running Static Code Analysis
          command: |
            make lint

      - run:
           name: Running Unit Test Suite
           command: |
             make test_unit

      - run:
           name: Running Integration Test Suite
           command: |
             make test_integration

  gke_dev_deploy:
    working_directory: ~/workspace
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout

      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_dev

  gke_staging_deploy:
    working_directory: ~/workspace
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout

      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_staging

workflows:
  version: 2
  main:
    jobs:
      - test:
          context: org-global
      - gke_dev_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - gke_staging_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/
