version: 2

jobs:
  test:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:3.6.4-stretch

    steps:
      - checkout

      # NOTE: these are temporary steps until moved to docker
      - run:
          name: Creating a virtual environment
          command: |
            python -m venv venv

      - run:
          name: Installing dependencies
          command: |
            source venv/bin/activate
            pip install -r requirements-test.txt

      - run:
          name: Running static code analysis
          command: |
            source venv/bin/activate
            PYTHONPATH=$(pwd) flake8 platform_storage_api tests
      - run:
          name: Running test suite
          command: |
            source venv/bin/activate
            PYTHONPATH=$(pwd) pytest -vv tests

  gke_dev_deploy:
    working_directory: ~/workspace
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_dev

  gke_staging_deploy:
    working_directory: ~/workspace
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      
      - run:
          name: GKE Auth
          command: |
            make -s gke_login

      - run:
          name: GKE Docker Push
          command: |
            make gke_docker_push

      - run:
          name: GKE K8s Deploy
          command: |
            make gke_k8s_deploy_staging

workflows:
  version: 2
  main:
    jobs:
      - test:
          context: org-global
      - gke_dev_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - fix_helm
      - gke_staging_deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - /release.*/
