NP_STORAGE_NFS_SERVER:
  _default: '172.27.83.58'
  dev: '172.27.83.58'
  staging: '10.69.59.50'
NP_STORAGE_NFS_PATH:
  _default: '/staging_premium'
  dev: '/staging_premium'
  staging: '/devpremium'
IMAGE:
  _default: gcr.io/light-reality-205619/platformstorageapi-k8s:latest
  dev: gcr.io/light-reality-205619/platformstorageapi-k8s:latest
  staging: gcr.io/light-reality-205619/platformstorageapi-k8s:latest
NP_STORAGE_AUTH_URL:
  _default: https://platform.dev.neuromation.io
  dev: https://platform.dev.neuromation.io
  staging: https://platform.staging.neuromation.io
