NP_STORAGE_NFS_SERVER: '10.76.126.154'
NP_STORAGE_NFS_PATH: '/dev2premium'
IMAGE: ''
NP_STORAGE_AUTH_URL: http://platformauthapi:8080
NP_STORAGE_REQUESTS_CPU: "0.1"
NP_STORAGE_LIMITS_CPU: "0.2"
NP_STORAGE_REQUESTS_MEMORY: "300Mi"
NP_STORAGE_LIMITS_MEMORY: "600Mi"
NP_STORAGE_REPLICAS: "2"
NP_PERMISSION_EXPIRATION_INTERVAL: "5"
NP_PERMISSION_FORGETTING_INTERVAL: "300"
