NP_STORAGE_NFS_SERVER:
  _default: '172.27.83.58'
  dev: '172.27.83.58'
  staging: '10.69.59.50'
NP_STORAGE_NFS_PATH:
  _default: '/staging_premium'
  dev: '/staging_premium'
  staging: '/devpremium'
IMAGE:
  _default: gcr.io/light-reality-205619/platformstorageapi-k8s:latest
  dev: gcr.io/light-reality-205619/platformstorageapi-k8s:latest
  staging: gcr.io/light-reality-205619/platformstorageapi-k8s:latest
NP_STORAGE_AUTH_URL:
  _default: http://platformauthapi:8080
  dev: http://platformauthapi:8080
  staging: http://platformauthapi:8080
NP_STORAGE_REQUESTS_CPU:
  _default: "0.3"
  dev: "0.1"
  staging: "0.1"
NP_STORAGE_LIMITS_CPU:
  _default: "0.5"
  dev: "0.2"
  staging: "0.3"
NP_STORAGE_REQUESTS_MEMORY:
  _default: "500Mi"
  dev: "300Mi"
  staging: "400Mi"
NP_STORAGE_LIMITS_MEMORY:
  _default: "1Gi"
  dev: "600Mi"
  staging: "800Mi"
NP_STORAGE_REPLICAS:
  _default: "2"
  dev: "2"
  staging: "2"

