permissionExpirationInterval: 60
permissionForgettingInterval: 600
keepAliveTimeout: 75

image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG

imagePullSecrets: []

replicas: 2

platform:
  clusterName:
  authUrl:
  token: {}

resources:
  requests:
    cpu: "0.1"
    memory: "400Mi"
  limits:
    cpu: "0.3"
    memory: "800Mi"

secrets: []

ingress:
  enabled: false

storages: []

cors: {}

zipkin: {}

sentry: {}
