NP_STORAGE_NFS_SERVER: ''
NP_STORAGE_NFS_PATH: ''
NP_STORAGE_PVC_CLAIM_NAME: ''
NP_STORAGE_AUTH_URL: http://platformauthapi:8080
NP_PERMISSION_EXPIRATION_INTERVAL: "60"
NP_PERMISSION_FORGETTING_INTERVAL: "600"
NP_STORAGE_ZIPKIN_URL: ''
NP_STORAGE_ZIPKIN_SAMPLE_RATE: '0.1'  # 10% of traces are saved
NP_STORAGE_SENTRY_URL: ''
NP_STORAGE_SENTRY_SAMPLE_RATE: '0.1'  # 10% of traces are saved
NP_CLUSTER_NAME: ''
NP_STORAGE_API_KEEP_ALIVE_TIMEOUT: "75"

image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

platform:
  token: {}

resources:
  requests:
    cpu: "0.1"
    memory: "400Mi"
  limits:
    cpu: "0.3"
    memory: "800Mi"

secrets: []

ingress:
  enabled: false
