permissionExpirationInterval: 60
permissionForgettingInterval: 600
keepAliveTimeout: 75

image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicas: 2

platform:
  clusterName:
  authUrl:
  adminUrl:
  token: {}

resources:
  requests:
    cpu: "0.1"
    memory: "400Mi"
  limits:
    cpu: "0.3"
    memory: "800Mi"

secrets: []

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

service:
  annotations: {}

storages: []

kube:
  namespace: "default"

sentry:
  appName: platform-storage
  sampleRate: 0.002

priorityClassName: ""

s3: {}
  # region:
  # accessKeyId: {}
  # secretAccessKey: {}
  # endpoint:
  # bucket:
  # keyPrefix:

storageUsageCollector:
  schedule: "0 * * * *" # every hour
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  resources:
    requests:
      cpu: "0.1"
      memory: "100Mi"
    limits:
      cpu: "0.3"
      memory: "200Mi"

metrics:
  replicas: 2

  resources:
    requests:
      cpu: "0.1"
      memory: "100Mi"
    limits:
      cpu: "0.2"
      memory: "200Mi"

  service:
    port: 8080

  serviceMonitor:
    enabled: true


admissionController:
  app_name: "storage-admission-controller"
  storage_admission_controller_tls_key:
    valueFrom:
      secretKeyRef:
        name: platform-storage-admission-controller
        key: tls-key
  storage_admission_controller_tls_cert:
    valueFrom:
      secretKeyRef:
        name: platform-storage-admission-controller
        key: tls-cert
  storage_admission_controller_ca_bundle:
    valueFrom:
      secretKeyRef:
        name: platform-storage-admission-controller
        key: ca-bundle
  service:
    port: 8080
