permissionExpirationInterval: 60
permissionForgettingInterval: 600
keepAliveTimeout: 900

platform:
  clusterName: default
  authUrl: http://platform-auth:8080
  adminUrl: http://platform-admin:8080
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: storage_token

ingress:
  enabled: true
  ingressClassName: traefik
  hosts: [dev.neu.ro]
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    external-dns.platform.neuromation.io: "true"

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_STORAGEAPI_SESSION

storages:
- type: pvc
  claimName: platform-storage

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev

priorityClassName: "platform-services"

aws:
  region: minio
  accessKeyId:
    valueFrom:
      secretKeyRef:
        name: minio-gateway
        key: root-user
  secretAccessKey:
    valueFrom:
      secretKeyRef:
        name: minio-gateway
        key: root-password
  s3EndpointUrl: http://minio-gateway:9000
  metricsBucketName: apolo-storage-metrics

storageUsageCollector:
  schedule: "*/5 * * * *"
