permissionExpirationInterval: 60
permissionForgettingInterval: 600
keepAliveTimeout: 900

platform:
  clusterName: default
  authUrl: http://platform-auth:8080
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: storage_token

ingress:
  enabled: true
  hosts: [dev.neu.ro]
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.platform.neuromation.io: "true"
    # TODO: remove traefik v1 annotations
    traefik.frontend.rule.type: PathPrefix

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_STORAGEAPI_SESSION
    # TODO: remove traefik v1 annotations
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_STORAGEAPI_SESSION

storages:
- type: pvc
  claimName: pvc-platform-storage

cors:
  origins:
  - http://localhost:8000
  - https://master--neuro-web.netlify.app
  - https://master--megafon-web.netlify.app
  - https://master--mts-web.netlify.app
  - https://master--minzdav-web.netlify.app

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
