permissionExpirationInterval: 60
permissionForgettingInterval: 600
keepAliveTimeout: 900

platform:
  clusterName: default
  authUrl: http://platformauthapi:8080
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: storage_token

ingress:
  enabled: true

  extraAnnotations:
    external-dns.platform.neuromation.io: "true"
  hosts: [dev.neu.ro]

storages:
- type: pvc
  claimName: pvc-platform-storage

cors:
  origins:
  - http://localhost:8000
  - https://master--neuro-web.netlify.app
  - https://master--megafon-web.netlify.app
  - https://master--mts-web.netlify.app
  - https://master--minzdav-web.netlify.app

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
