apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.admissionController.app_name }}
  labels:
    {{- include "platformStorage.labels.standard" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.admissionController.app_name }}
  labels:
    {{- include "platformStorage.labels.standard" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.admissionController.app_name }}
  labels:
    {{- include "platformStorage.labels.standard" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.admissionController.app_name }}
    namespace: platform
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Values.admissionController.app_name }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.admissionController.app_name}}
  labels:
    {{- include "platformStorage.labels.standard" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.admissionController.app_name}}
  labels:
    {{- include "platformStorage.labels.standard" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.admissionController.app_name}}
    namespace: platform
roleRef:
  kind: ClusterRole
  name: {{ .Values.admissionController.app_name}}
  apiGroup: rbac.authorization.k8s.io
