apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformStorage.fullname" . }}
  labels:
    {{- include "platformStorage.labels.standard" . | nindent 4 }}
    service: platform-storage
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "platformStorage.name" . }}
      release: {{ .Release.Name }}
      service: platform-storage
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platformStorage.name" . }}
        release: {{ .Release.Name }}
        service: platform-storage
      {{- if .Values.secrets }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- end }}
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
          {{- include "platformStorage.env" . | nindent 10 }}
        - name: NP_STORAGE_EVENTS_URL
          value: {{ .Values.platform.eventsUrl }}
        - name: NP_STORAGE_EVENTS_TOKEN
          {{- if .Values.platform.token }}
          {{ toYaml .Values.platform.token | indent 10 }}
          {{- end }}
        {{- if .Values.storages }}
        volumeMounts:
          {{- include "platformStorage.volumeMounts" . | nindent 10 }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.storages }}
      volumes:
        {{- include "platformStorage.volumes" . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
