name: CI

on:
  push:
    branches: [dsmyk/deployment]
    tags: [v*.*, v*.*.*]
  pull_request:
    branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Cache packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py-3.9-${{ hashFiles('setup.cfg') }}
    - name: Install dependencies
      run: make setup
    - name: Login to ghcr.io
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
#    - name: Lint
#      run: make lint
#    - name: Run unit tests
#      run: make test_unit
#    - name: Run integration tests
#      run: make test_integration
    - name: Build Docker image
      run: make build/image
    - name: Upload image artifact
      uses: neuro-inc/upload-image-action@v24.4.0
      with:
        image: platformstorageapi
        token: ${{ secrets.GITHUB_TOKEN }}

  approve:
    name: Approve bot PR
    runs-on: ubuntu-latest
    if: endsWith(github.actor, '[bot]')
    needs: test
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: metadata
      id: metadata
      if: github.actor == 'dependabot[bot]'
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Enable auto-merge for bot PRs
      run: gh pr merge --auto --squash --delete-branch "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create release
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/dsmyk/deployment' || startsWith(github.ref, 'refs/tags/'))
    uses: neuro-inc/reuse/.github/workflows/release-service.yaml@v24.10.0
    with:
      image: platformstorageapi
      helm_charts: platform-storage

#  deploy:
#    name: Deploy
#    needs: release
#    if: github.event_name == 'push' && github.ref == 'refs/heads/dsmyk/deployment'
#    uses: neuro-inc/reuse/.github/workflows/deploy-service.yaml@v24.10.0
#    secrets:
#      tf_api_token: ${{ secrets.TF_API_TOKEN }}
#    with:
#      environment: dev
#      dev_workspace: ${{ vars.DEV_TFC_WORKSPACE_JSON }}
#      variables: |
#        platform_storage_version=${{ needs.release.outputs.version }}
