name: Release Image

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    concurrency: release_image
    steps:
    - name: Release image
      id: release
      uses: neuro-inc/release-image-action@v21.9.36
      with:
        image: platformstorageapi
        token: ${{ secrets.GH_TOKEN }}
    - name: Github Release
      if: ${{ ! steps.release.outputs.skip }}
      run: |
        if [[ -n $PRERELEASE ]]; then
          gh release create ${{ steps.release.outputs.tag }} --prerelease --notes Release
        else
          gh release create ${{ steps.release.outputs.tag }} --notes Pre-Release
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PRERELEASE: ${{ steps.release.outputs.prerelease }}
