name: Release

on:
  release:
    types: [published]

jobs:

  test:
    name: Run  Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'GITHUB_REF=refs/tags/test_release')
    env:
      PIP_INDEX_URL: ${{ format('https://{0}:{1}@{2}/{0}/{3}', secrets.DEVPI_USER, secrets.DEVPI_PASS, secrets.DEVPI_HOST, secrets.DEVPI_INDEX) }}
      IMAGE_REPO : ${{ format('{0}.dkr.ecr.{1}.amazonaws.com', secrets.AWS_ACCOUNT_ID, secrets.AWS_REGION) }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Show all envs
        run: env | sort


  deploy_artifactory:
    name: Deploy on Artifactory
    runs-on: ubuntu-latest
#    needs: test
    if: startsWith(github.ref, 'refs/heads/release123/')
    env:
      PIP_INDEX_URL: ${{ format('https://{0}:{1}@{2}/{0}/{3}', secrets.DEVPI_USER, secrets.DEVPI_PASS, secrets.DEVPI_HOST, secrets.DEVPI_INDEX) }}
      ARTIFACTORY_DOCKER_REPO: ${{ secrets.ARTIFACTORY_DOCKER_REPO }}
      ARTIFACTORY_HELM_REPO: ${{ secrets.ARTIFACTORY_HELM_REPO }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Artifactory Docker Push
        run: make artifactory_docker_push
      - name: Artifactory Helm Push
        run: make artifactory_helm_push
