name: Release Image

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    concurrency: release_image
    steps:
    - name: Checkout commit
      uses: neuro-inc/release-image-action@v21.9.31
      with:
        github: ${{ toJson(github) }}
        image: platformstorageapi
        token: ${{ secrets.GH_TOKEN }}
